 version: '3.7'

 services:
   db:
     image: mysql:5.7
     container_name: mysql_db
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: rootpsw
       MYSQL_DATABASE: laravel
       MYSQL_USER: admin
       MYSQL_PASSWORD: adminpsw
     ports:
       - "3306:3306"
     volumes:
       - db_data:/var/lib/mysql

 volumes:
   db_data:
#version: '3.8'

#services:
#  db:
 #   image: postgres
  #  restart: always
   # environment:
    #  POSTGRES_PASSWORD: example
     # POSTGRES_USER: user
      #POSTGRES_DB: database_name
    #ports:
     # - "5432:5432"
    #volumes:
     # - postgres_data:/var/lib/postgresql/data

  #pgadmin:
   # image: dpage/pgadmin4
    #restart: always
    #environment:
    #  PGADMIN_DEFAULT_EMAIL: admin@example.com
    # PGADMIN_DEFAULT_PASSWORD: admin
   # ports:
    #  - "5050:80"
    #volumes:
      - pgadmin_data:/var/lib/pgadmin

#volumes:
 # postgres_data:
  #pgadmin_data:

